### PR TITLE
fix: can not find SketchRnn on case-sensitive file system(linux)

### PR DESCRIPTION
**Pull request by snowyu**

### CODE REVIEW

**Comment by tlsaeger** [comment]
Hey @snowyu thanks for the PR, it is highly appreciated. Could you be so kind and write a little bit about the what exactly you are fixing and how. This will help us further down the line, to keep an overview. 
Thanks and have a good one!

**Comment by snowyu** [comment]
```bash
# Can not work on linux(ext4 file system)
npm run download:all

ml5-data-and-models-server@0.0.1 download:all ~/ml5js/ml5-data-and-models-server
> node ./scripts/download-models/index.js all

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './SketchRnn'
```

**Comment by omar2205** [comment]
IDK why this PR wasn't accepted, the script thinks there is a dir `SketchRnn` in `scripts/download-models`
But it's called `SketchRNN`

**Comment by tlsaeger** [comment]
Hi @omar2205 and @snowyu apologies for late reply. Need to ping @shiffman @bomanimc to approve this request. As I'm not that deep into the data-and-models-server project.

**Comment by shiffman** [comment]
Yes, this is great! Thank you so much for the contribution!!

**Pull request merged**
